version: '3.9'

# Services
services:
 # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - './html:/var/www/html'
    depends_on:
      - mariadb
# Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 88:80
    links:
      - 'php'
    volumes:
      - './html:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
  # MariaDB Service
  mariadb:
    image: mysql:latest
    #image: mysql:latest
    environment:
      #MYSQL_DATABASE: m4prog
      #MYSQL_USER: m4proggebruiker
      #MYSQL_PASSWORD: bf83tb3g5v
      #MYSQL_ROOT_PASSWORD: 4dy5qwtrsag#!sad
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL ROOT PASSWORD: ${DB ROOT PASSWORD}
    ports:
      - 3308:3306

  # php myadmin in an external image
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      #PMA_HOST: mariadb
      #PMA_USER: m4proggebruiker
      #PMA_PASSWORD: bf83tb3g5v
      PMA HOST: ${DB_HOST}
      PMA USER: ${DB_USER}
      PMA PASSWORD: ${DB PASSWORD}
    ports:
      - "1088:80"

# Volumes
volumes:
  mysqldata: